# Generated by Django 4.0.1 on 2022-03-11 13:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='date_of_birth',
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(default='shah', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
