# Generated by Django 4.0.1 on 2022-03-14 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_first_name_user_is_customer_user_is_seller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_customer',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_seller',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
    ]
